sudo: true
language: node_js
before_install:
- source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
- wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
- sudo apt-get update
- sudo apt-get install rethinkdb
install:
  - npm install
  - npm install mocha
  - npm install request
#before_script:
#  - npm run configure:db
addons:
  rethinkdb: '2.3.5'
node_js:
  - 'node'
  - '6'
  - '5'
  - '4'
